from enum import Enum


class AssistantIntent(str, Enum):
    RECOMMEND_BEVERAGE = "RECOMMEND_BEVERAGE"
    FIND_NEARBY_VENUE = "FIND_NEARBY_VENUE"
    COMPARE_PURCHASE_OPTIONS = "COMPARE_PURCHASE_OPTIONS"
    EXPLAIN_PREFERENCE = "EXPLAIN_PREFERENCE"
    EXPLAIN_RECOMMENDATION = "EXPLAIN_RECOMMENDATION"
    PROFILE_STATUS = "PROFILE_STATUS"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
